FROM node:20-alpine as BUILD_IMAGE

WORKDIR /app/react-app

COPY package.json -

RUN npm install

COPY - -

RUN npm run build 

FROM node:20-alpine as PRODUCTION_IMAGE
WORKDIR /app/react-app

COPY --from=BUILD_IMAGE /app/react-app/dist/ /app/react-app/dist

EXPOSE 3000

COPY package.json -
COPY vite.congig.js -

RUN npm install javascript
EXPOSE 3000

CMD [ "npm","run","preview" ]

# docker build -t vite-lava-app:latest -
# docker image | grep -t vite-lava-app
# docker run -p 3000:3000 vite-lava-app:latest