version: '3'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  server:
    build: server
    environment:
      - MONGO_URI=mongodb+srv://mohamedwael4553:iraQjWuaCQpe3Czo@cluster0.s4o9nrn.mongodb.net/Lava
      - PORT=5000
      - JWT_SECRET = hvdvay6ert72839289()aiyg8t87qt72393293883uhefiuh78ttq3ifi78272jbkj?[]]pou89ywe
      - NODE_ENV = production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_MAIL=mohamedwael4553@gmail.com
      - SMTP_PASS=jggc gzru ngsx ozir
      - USER_VERIFICATION_TOKEN_SECRET=dgfgpspdifgskdfngussj490385jsp8ms
      - GOOGLE_CLIENT_ID=107xxx-ni31ps789mf1jd33nnfk57vdllhqcmie.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=KE5xxxvvm
      - GOOGLE_CALLBACK_URL=http://localhost:5000/api/auth/google/callback
      - CLIENT_URL=http://localhost:5000/api
      - BASE_API_URL=http://localhost:5000
      - BASE_API_URL_HOST=api
    ports:
      - '5000:5000'
